name: CI


on: [push, pull_request]


jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'
